### ISSUE TITLE
[Feature] Automatyczna aktualizacja skryptu

### ISSUE THREAD

**Issue by Bombowacena** [picakia/allegro-rozlacz-oferty#1]
**Opis błędu**
Rzeczywiście po aktualizacji kodu już nie zawiesza w tym linku co podałem w Allegro społeczność
Dzięki za dobrą robotę. W kontakcie

PS. czy w Tampermonkey w ustawieniach tego skryptu można ustawić Adres URL aktualizacji? żeby było można to robić z automatu?
czy taki będzie prawidłowy? https://github.com/picakia/allegro-rozlacz-oferty/blob/master/AllegroRozlaczV2.js

**Comment by picakia** [comment]
Faktycznie, można ustawić url. Poprawny link to będzie: https://raw.githubusercontent.com/picakia/allegro-rozlacz-oferty/refs/heads/master/AllegroRozlaczV2.js

**Comment by picakia** [comment]
Instrukcja zaktualizowana w Readme, zamykam.
