### ISSUE TITLE
[BUG] Nie działa w MS Edge 129.0.2792.79

### ISSUE THREAD

**Issue by 0x8008** [picakia/allegro-rozlacz-oferty#2]
**Opis błędu**
Skrypt robi całe nic po zainstalowaniu w Tampermonkey w Edge 129.0.2792.79

**Link**
Przykładowe wyszukiwanie: https://allegro.pl/kategoria/nintendo-switch-konsole-256863?string=nintendo%20switch%20hac-001

**Zrzut ekranu**
![image](https://github.com/user-attachments/assets/28211e65-5b4b-44c6-8227-89ed0c520ab5)

**Platforma**
 - System: Win11 x64 22h2
 - Przeglądarka: Edge 129
 - Wersja skryptu: 2024-10-12_18-34

**Dodatkowe informacje**
n/d

**Comment by picakia** [comment]
Sprawdziłem u siebie i działa bez zarzutu, upewnij się, że zainstalowałeś Tampermonkey ze strony microsoft: https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd
![image](https://github.com/user-attachments/assets/9d56ddb3-e9c1-4b56-a8da-d0fb675bbbaa)

U mnie działa nawet bez trybu deweloperskiego, ale gdyby dalej był problem to możesz uruchomić tryb deweloperski w menu rozszerzeń:
![image](https://github.com/user-attachments/assets/eddc835a-d394-4806-9463-a8b31d1ce171)

**Comment by picakia** [comment]
Na razie zamykam, w razie dalszych problemów można będzie otworzyć ponownie
